name: Build Obfuscate BPB Panel

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 1 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install obfuscator
        run: npm install -g javascript-obfuscator@4.0.0

      - name: Download latest origin.js (temp)
        run: wget -O temp_origin.js https://raw.githubusercontent.com/bia-pain-bache/BPB-Worker-Panel/refs/heads/main/build/unobfuscated-worker.js

      - name: Obfuscate BPB worker js
        run: |
          javascript-obfuscator temp_origin.js --output _worker.js \
          --compact true \
          --control-flow-flattening false \
          --dead-code-injection false \
          --identifier-names-generator hexadecimal \
          --rename-globals true \
          --string-array true \
          --string-array-encoding 'base64' \
          --string-array-threshold 0.75 \
          --transform-object-keys true \
          --unicode-escape-sequence true

      - name: Auto commit _worker.js if changed
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: ':arrow_up: daily update _worker.js'
          file_pattern: _worker.js
          commit_author: 'github-actions[bot] <github-actions[bot]@users.noreply.github.com>'
